### ISSUE TITLE
The experimental results on KITTI 00 sequence is not good.

### ISSUE THREAD

**Issue by xiaobrnbrn** [url-kaist/AlterGround-LeGO-LOAM#4]
Great work! I have tested this project with KITTI-odometry 00 sequence, but I found that the result was not as good as I expected. The mapping results can be found as follows, where the top one is created by PaGO-LOAM, and the bottom one is generated by original lego-loam. It can be seen that the results  of PaGO-LOAM suffers from larger drift errors, what would be the reasons for this? Could you please share the param settings utilized in the corresponding paper?

![Screenshot from 2022-10-05 11-14-30](https://user-images.githubusercontent.com/30363654/193975190-c71c89a2-8db1-47a9-b383-64cf3d6b4ef5.png)
![Screenshot from 2022-10-05 11-16-36](https://user-images.githubusercontent.com/30363654/193975196-dd202270-633a-406f-bebf-fdfe5321f5c1.png)

**Comment by fwailiu** [comment]
@xiaobrnbrn 你好，我现在在复现pego-loam，但是我在播放pago-loam的时候，一点反应都没有

**Comment by xiaobrnbrn** [comment]
> @xiaobrnbrn 你好，我现在在复现pego-loam，但是我在播放pago-loam的时候，一点反应都没有

您好，有什么问题请详细说明，最好把你的操作过程和遇到的问题直接贴出来
